### ISSUE TITLE
Input selection on MCTRL4K

### ISSUE THREAD

**Issue by cdmlehigh** [bitfocus/companion-module-novastar-controller#6] opened 2020-06-24 22:57 UTC
Hello-

The "Input selection" does not seem to be working for me. 

I can confirm that the brightness commands and "display mode" commands DO work. 

Somebody named "Pixel Jedi" is offering their own builds for Windows and macOS-- the commands in their build seem to work, however they're using an alpha build of Companion, and I do not trust it. 

Any ideas?

Thank you,
Christian

**Comment by krocheck** [comment] 2020-06-24 23:47
The 2.0 beta builds available through the Bitfocus website are considered stable at this point, we just haven't had a chance with other things going on to package a formal release.  There was a re-write of the module compared to what was in v1.4, which is likely what you're seeing.  That alpha build should be one and the same to our beta builds, but I'd generally recommend grabbing them from us.

**Comment by cdmlehigh** [comment] 2020-06-25 00:13
Thanks for your quick response.  The build I'm using (where the input commands don't work) is the latest beta (ce59ecb-2424)

The custom build that I found (and seems to work properly) is based off of 8fe2222-1983.

**Comment by krocheck** [comment] 2020-06-25 00:44
Interesting.  Do you have a link to this alpha build or their module code?

I did some development on this module, but all the control strings came from other people and I have no way of testing.  Hopefully other people more knowledgeable with Novastar equipment can jump in on this.

I know Novastar is very difficult because everything has to be reverse engineered ... they don't provide any protocol documentation for 3rd party development.

**Comment by cdmlehigh** [comment] 2020-06-25 01:03
http://www.pixeljedi.solutions/wp-content/uploads/2020/companion/companion-win64.exe.zip

If it's any help, I have access to most Novastar products and would be glad to help test.

**Comment by krocheck** [comment] 2020-06-25 01:14
You've jogged my memory and I am aware of this.

Which instance type are you using in the Pixel Jedi build?  There's a 'Novastar all" and "Novastar MCTRL4k".  Also, in our build did you use the "Novastar MCTRL4K" instance AND select that as the model when setting the IP address in the instance config?

**Comment by cdmlehigh** [comment] 2020-06-25 11:53
Both instance types work in the Pixel Jedi build.

In the official build, I am indeed using the "Novastar MCTRL4K" instance and selecting that model in the instance config.  No luck.

**Comment by rit3sh7** [comment] 2020-08-02 02:06
so I am "pixel Jedi" I wrote that code for both my own build as we were waiting for a companion to accept the code into the final build.  Both codes should be the same, someone else had changed structure on a new build on companion but once I get a chance I will check it. I do have all processors and it was all tested by myself.  @krocheck  they do provide all protocols after you sign NDA with them Just FYI and if you need them let me know.

**Comment by Thymeauthe** [comment] 2023-02-15 17:18
Hello,

I have tested MCTRL4K too. On the last confirmed version of companion (2.4.2), I only find "Change Test Pattern" and "Change Display Mode" as actions.

I test VS4X and I find all actions of the description module.
Is any body have an idea why it doesn't work on MCTRL4K ?

**Comment by rit3sh7** [comment] 2023-02-15 17:21
MCTRL4k is Sending card which does not have scanning and all other functions as other VX4S as that is Video processor with sending card. If the actions don’t exist on your model it won’t work of course.

**Comment by Thymeauthe** [comment] 2023-02-18 09:26
MCTRL 4K have some different inputs like VX4S or others.

So why can’t we use the « change input » module ?

**Comment by rit3sh7** [comment] 2023-02-19 02:31
Go ahead and add the code for it if you know how to do that, you have clear idea of what you need. This is an open source app which means anyone can edit the code to do what they desire to do.

**Comment by istnv** [comment] 2023-09-02 22:41
Available/fixed in  PR #44

**Closed by istnv** 2023-09-02 22:41 UTC
